### ISSUE TITLE
failed start of app

### ISSUE THREAD

**Issue by EugeneBogush** [uw-ictd/haulage#19]
# haulage 
INFO[0000] Starting haulage                             
INFO[0000] Parsed parameters                             Parameters="{20m0s 1m0s enp1s0 {5s colte_db colte_db colte_db}}"
INFO[0000] Initializing context                         
ERRO[0000] Unable to query initial bridged state         error="Error 1146: Table 'colte_db.customers' doesn't exist"

**Comment by spencersevilla** [comment]
@EugeneBogush sorry for this! I'm currently re-architecting some code that relates to package and database management. I'm hoping to get this out in the next week or two, and will comment back on this issue when I do. In the meantime I will add a box-note to the README that makes this clear.

**Comment by EugeneBogush** [comment]
resolved to
